### ISSUE TITLE
 Memory leak cause WiFi Slow after 2-3 days until reboot?

### ISSUE THREAD

**Issue by MaurUppi** [SVoxel/ORBI-RBK50#2]
Hi SVoxel

I'm sorry to trouble you that can you take your time to investigate below detail discussion thread ?
https://community.netgear.com/t5/Orbi/WiFi-Slow-after-2-3-days-until-reboot/td-p/1782582
BTW: that why i start another thread to report how to use crontab to setup schedule reboot to workaround wifi speed drop issues. But we need fundamental solutions. 
Will you help to figure out what cause this issues?

Let me try to summary for you which is :
1. Many RBK50/53 users has WIFI slow down issues, most issue happen on Router (RBR50) but not Satellite (RBS50).
2. Most of them tried update to latest firmware or like me is using your RBK50-V9.2.5.1.11SF-HW also has same issues.
3. After reboot, 5G WIFI speed work fine as expect as 5G standard.
4. e.g every 2-3 days though, WiFi speeds drop from 180+ Mb/s down to to ~40 Mb/s
5. Most of cause has been eliminated, such like channel settings, wired or wireless backhaul, other device broadcasting issue.
6. Some person guessing is memory leak or similar cause.

**Comment by SVoxel** [comment]
The same note: please contact in the future in SNB forums. 

Check the message 

https://www.snbforums.com/threads/custom-firmware-build-for-orbi-rbk50-rbk53-rbr50-rbs50-v-9-2-5-1-9sf-hw.60727/page-3#post-539113

This guy had the same problem. You can check all his messages (7 total). Maybe you have to reset to factory, flash stock 2.5.1.8 and back to my version if you want.

I do not think that there is memory leakage. E.g. my Orbi worked about 20 days w/o reboot and no problems. It does not eat the RAM.

Voxel.
